### ISSUE TITLE
Spiel erstellen Fehlermeldungen anzeigen

### ISSUE THREAD

**Issue by TheExecutor** [s1lobnig/DI-4_ScotlandYard#35]
Wird beim Erstellen eines Servers keine maximale Teilnehmeranzahl angegeben, stürzt die App ab. Eine Aufforderung an den User, eine Zahl anzugeben, wird gefordert.

**Comment by LordDeSith** [comment]
Als Spieler möchte ich, dass beim Spiel erstellen eine Fehlermeldung angezeigt wird, falls kein Servername, Spielername und max. Spieleranzahl eingegeben wird.
